### ISSUE TITLE
Movie List Suggestions

### ISSUE THREAD

**Issue by RicardoVelaC** [Flexget/webui#95]
With the new WebUI_v2 the `Movie List` section is unusable, I found some errors and improvements.

1. The section load slowly, maybe because image request for all items.
> In **WebUI_v1** the images store in cache folder at first time, for the second time it uses the cache, 
In **WebUI_v2** saves the image to cache but never uses it.

2. I can ADD a new Movie using the local title, Spanish e.g., but always show the English title only show the Spanish title if english doesn't exist. This is very confusing to find an element. (Fixed in #108)

3. Now I can see all the items as individual cards, it show the blackdrop as image but not all movies has it, especially premieres items, maybe if always show the main poster it will be more intuitive and user-friendly. And if it were possible to add an option to see all items as a list view, it would be very fast and interesting for when you have to show many items.

**Comment by kristenmills** [comment]
Thanks for the feedback. To respond to each of your points:

1.  I agree that it is slower because it makes requests to multiple services. This is already on my radar to improve. (in the future you will be able to configure which lookups you do for movies. 

> In WebUI_v1 the images store in cache folder at first time, for the second time it uses the cache,
In WebUI_v2 saves the image to cache but never uses it. 

What is giving you the impression that it is not using the cache? I'm not seeing that behavior.

2. Did webui v1 support this properly? I agree that we should support localization better, especially since we get this data from the lookups, but might require additional configuration to know which language to choose. 

3.  It should fall back to a poster if there is no backdrop. Mind providing me an example movie where you are seeing this behavior?

**Comment by RicardoVelaC** [comment]
Thanks for answer:

1. I don't know exactly if it uses the cache or not, but in my case `movieList` wait about 12 seconds for 24 items, and don't show anything until it's all loaded. You are right it makes to many requests. A progressive load maybe will be better for speed it.

2. Yes in v1 when I search in Spanish show the item in Spanish, I remember it like this (Now I can't access to v1, load the login but never autenticate). It's so confusing.
Add an option for choose default language parameter will be an advantage.

3. Yes it shows the poster if there is no backdrop, but this situation it a little confusing, some backdrop has text, other only image. 
<img width="900" alt="flexget" src="https://user-images.githubusercontent.com/6016812/74422346-c05da680-4e4e-11ea-93f0-7a30ecebbef4.png">

4. Maybe an option for improve it and make it load faster it's add a new view for `movieList` for show it like a dynamic table with only text and the ability to order by columns, it make it faster and useful for order items by years, name, duration or genre.

**Comment by RicardoVelaC** [comment]
I can confirm, I access to v1 and the titles show in my language like I added them.
<img width="858" alt="movie" src="https://user-images.githubusercontent.com/6016812/74427230-f737ba80-4e56-11ea-8d6e-075ffb36491d.png">
With the v1 `movieList` is faster, simple and look better with the poster. It's my opinion. But v2 it the way we can to improve it :-)

**Comment by kristenmills** [comment]
Cool thanks for the details i'll probably triage these into separate issues soon.
